import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${quicksand.variable} antialiased h-full overflow-hidden`}
      >
        <div className="flex flex-col h-full">
          <Navbar />
          <div className="flex-grow overflow-y-auto mt-[8rem]">
            <div className="max-w-[1440px] w-full mx-auto h-[calc(100% - 8rem)]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
