import type { Metadata } from "next";
import { DM_Sans, Playfair_Display, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"]
})

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"]
})

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${spaceGrotesk.variable} ${dmSans.variable} ${playfairDisplay.variable} antialiased h-full overflow-hidden`}
      >
        <div className="flex flex-col h-full">
          <Navbar />
          <div className="flex-grow overflow-y-auto mt-[8rem]">
            <div className="max-w-[1440px] w-full mx-auto h-[calc(100% - 8rem)]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
