services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=nowastee'
      - 'POSTGRES_PASSWORD=docker'
      - 'POSTGRES_USER=docker'
    volumes:
      - 'nowastee_pg_data:/bitnami/postgresql'
    ports:
      - '8000:5432'

volumes:
  nowastee_pg_data: