name: CI Projeto Frontend No.wasTee

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-react:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar build do projeto (opcional)
        run: npm run build

      - name: Rodar testes com Vitest
        run: npx vitest run

      - name: Validar HTML (se aplicável após build)
        run: npx html-validate "build/**/*.html"
