name: CI Projeto Frontend No.wasTee

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Validar HTML com html-validate
        run: npx html-validate "build/**/*.html"

#      - name: Rodar testes com status personalizado
#        run: |
#          echo "Rodando testes..."
#          if npm test -- --watchAll=false; then
#            echo "Resultado: ✅ OK"
#          else
#            echo "Resultado: ❌ NOOK"
#            exit 1
#          fi
